chequear 1 twit: funcionalidad básica y medio rota
catdevnull/milei-twitter pull request #50
Opened 2024-03-20 03:48 UTC by Gahen

2024-03-27 01:39 UTC, Gahen commented on sitio/src/routes/+page.server.ts
> +      return dayjs().subtract(23, "hour");
Esto ni idea, se habrá cruzado con un cambio tuyo? Lo deshago?

2024-03-27 01:40 UTC, Gahen commented on sitio/src/routes/Footer.svelte
> +<footer class="flex flex-col gap-4 text-center">
Para mi habría que tener una carpeta de componentes pero respeté la estructura de tirarlos en este carpeta.

2024-03-27 02:07 UTC, catdevnull requested changes
buen comienzo!

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/+page.server.ts
> +      return dayjs().subtract(23, "hour");
es este commit https://github.com/catdevnull/milei-twitter/commit/a51b26c65cc2a1a51e120882039c010248f3e92d

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.server.ts
> +  const test = url.searchParams.get("test");
habría que parchear urls que sean de `x.com`

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.server.ts
> +  const test = url.searchParams.get("test");
también habría que sacar todos los query parameters. yo la parsearia `new URL(test)` para hacer estos cambios

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.server.ts
> +      search = await db.query.likedTweets.findMany({
findOne

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +  export let fecha = data.found?.length ? dayjs(data.found[0].firstSeenAt + "").format("YYYY-MM-DD") : ""
```suggestion
  $: fecha = data.found?.length ? dayjs(data.found[0].firstSeenAt + "").format("YYYY-MM-DD") : ""
```

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +  export let sinChequear = data.found === null // si no vino info está para chequear
```suggestion
  $: sinChequear = data.found === null // si no vino info está para chequear
```

estas dos son variables reactivas a partir de `data`, asi que tienen que ser declaradas con `$: `. `export let` es para propiedades que vienen de afuera ("props")

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +  let test = $page.url.searchParams.get("test");
```suggestion
  $: test = $page.url.searchParams.get("test");
```

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +        { sinChequear ? "Chequear" : "Chequeado"}
usar `{#if}` https://svelte.dev/docs/logic-blocks#if

2024-03-27 02:07 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +        { sinChequear ? "" : (data.found && data.found[0] ? `✓ Sí, fue likeado el ${fecha}` : "No fue likeado por Milei ❌")}
usar {#if} [svelte.dev/docs/logic-blocks#if](https://svelte.dev/docs/logic-blocks#if)

2024-03-27 02:09 UTC, catdevnull requested changes

2024-03-27 02:09 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +        { sinChequear ? "" : (data.found && data.found[0] ? `✓ Sí, fue likeado el ${fecha}` : "No fue likeado por Milei ❌")}
cambiaría el lenguaje acá para explicar (quizás en un párrafo abajo o algo así) que tiene que ser un tweet desde que tenemos dataset (10 de febrero) y aparte que esta es una herramienta experimental y podría llegar a fallar.

2024-03-27 02:09 UTC, catdevnull commented on sitio/src/routes/chequear/+page.svelte
> +        { sinChequear ? "" : (data.found && data.found[0] ? `✓ Sí, fue likeado el ${fecha}` : "No fue likeado por Milei ❌")}
se le podría poner la hora y minuto exacto que lo vimos por primera vez

2024-03-28 21:59 UTC, catdevnull commented
sigue en #51

2024-03-28 21:59 UTC, closed without merging